services:
  - type: web
    name: ocr-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    scaling:
      minInstances: 1
      maxInstances: 1 