services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata/
      - key: PATH
        value: /usr/bin:/usr/local/bin:/usr/share/tesseract-ocr/
      - key: PYTHONUNBUFFERED
        value: "true" 