services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    packages:
      - tesseract-ocr
      - libtesseract-dev 